export const GET_INVEST_CURRENT = "GET_INVEST_CURRENT";

export const GET_LIST_PACKAGE_INVESTMENT = "GET_LIST_PACKAGE_INVESTMENT";

export const SET_INVEST_CURRENT = "SET_INVEST_CURRENT";

export const SET_LIST_PACKAGE_INVESTMENT = "SET_LIST_PACKAGE_INVESTMENT";

export const BUY_INVESTMENT = "BUY_INVESTMENT";

export const HISTORY_INVESTMENT = "HISTORY_INVESTMENT";
