export const WITHDRAW_EARN = "WITHDRAW_EARN";

export const GET_COMMISSION_MEMBER = "GET_COMMISSION_MEMBER";

export const GET_COMMISSION_REF = "GET_COMMISSION_REF";

export const HISTORY_D_INVEST = "HISTORY_D_INVEST";
