export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const GENERATE_QR = "GENERATE_QR";
export const ACTIVE_AUTHENTICATOR = "ACTIVE_AUTHENTICATOR";
export const ON_CHANGE_SECURITY = "ON_CHANGE_SECURITY";
export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const VERIFY_EMAIL = "VERIFY_EMAIL";
