export const WITHDRAW = "WITHDRAW";

export const SWAP = "SWAP";

export const GET_MORE = "GET_MORE";

export const VERIFY_TRANSACTION = "VERIFY_TRANSACTION";

export const GET_TRANSACTIONS = "GET_TRANSACTIONS";

export const CANCEL_TRANSACTION = "CANCEL_TRANSACTION";
